### ISSUE TITLE
Draft a system for adding replies to reviews

### ISSUE THREAD

**Issue by MakotoE** [bcfoodapp/streetfoodlove#108]

**Comment by MakotoE** [comment]
# Design proposal

![comments](https://user-images.githubusercontent.com/36318069/150698164-75337266-2ab7-4fbe-8726-3569587d18e6.png)

# Table schema

```
CREATE TABLE Reviews (
  ID CHAR(36) NOT NULL,
  ReplyTo CHAR(36) NULL,
  ...
  FOREIGN KEY (ReployTo) REFERENCES Reviews(ID)
)
```

If this review is a reply to another review, ReplyTo contains the ID of the parent review. ReplyTo is NULL if this is a root review. A root review is not a reply to another review.

StarRating is NULL if reviewer did not give a rating.

# Example scenario

![replies](https://user-images.githubusercontent.com/36318069/150698394-3ce653a6-b424-41de-8b31-f108a99fc42e.svg)

Given review ID "A", how do you write a query to get a list of all replies for that review?

```
SELECT * FROM Reviews WHERE ReplyTo="A"
```

**Comment by czhou578** [comment]
Reply to isn't currently implemented in backend as of 1/31/2022
