### ISSUE TITLE
Design dashboard trends page

### ISSUE THREAD

**Issue by MakotoE** [bcfoodapp/streetfoodlove#197]
One of the pages that the vendor has access to are trends which contain various visualizations of data. The draft for this page should specify what graphs would display which data sets. The data set doesn't necessary have to exist yet as we can plan to collect that data in the future. We are planning to use [react-vis](https://uber.github.io/react-vis/) for data visualization.

**Comment by Wenhuan2516** [comment]
[Dashboard_Design.pdf](https://github.com/bcfoodapp/streetfoodlove/files/8128074/Dashboard_Design.pdf)
This is the design I made after discussed with Silvia. We think graph 4 should be the first one to implement.

**Comment by MakotoE** [comment]
Very good. Please specify the data sources as well, as in which column(s) of which tables are necessary for each graph.

**Comment by Wenhuan2516** [comment]
Yea, I will discuss with Silvia tonight to determine the data source, and then we will update the SDD documents with the data source information as well as the graphs
