### ISSUE TITLE
New review notification design

### ISSUE THREAD

**Issue by Wenhuan2516** [bcfoodapp/streetfoodlove#200]

**Comment by MakotoE** [comment]
User story:

- When the vendor opens their vendor dashboard, if new reviews were made after they checked the notifications, an indicator will appear on the "New Reviews" card on the dashboard.
- When the vendor opens the "New Reviews" page from their dashboard, any new reviews are listed on that page.

**Comment by Wenhuan2516** [comment]
I can imagine what it should look like. Don't really know how I should do to implement this feature yet

**Comment by MakotoE** [comment]
I changed the responsibility from you to myself because you have another task to work on. There are also easier tasks in Sprint 2, so I decided that I should work on this which is more complex.

**Comment by Wenhuan2516** [comment]
I see. Thank you so much! I did not realize it was so hard to implement this feature at first. I will work on other features then.

**Comment by MakotoE** [comment]
# Mockups

![Screenshot from 2022-04-08 18-34-32](https://user-images.githubusercontent.com/36318069/162551715-06f5b692-c95b-4ead-b388-5f5fdf2e3b10.png)

![Screenshot from 2022-04-08 18-42-18](https://user-images.githubusercontent.com/36318069/162551713-f7ff63a3-50a5-4bdd-8f8c-403feb43c153.png)

**Comment by MakotoE** [comment]
# Design

Add `LastReviewSeen` column to `User` table. `LastReviewSeen` is a nullable foreign key for `Reviews`. It indicates which review was the last one that the vendor has seen. It is null if the vendor page has no reviews or the user is a customer.

The table schema looks like:

```
User (
  ID CHAR(36) NOT NULL,
  ...
  LastReviewSeen CHAR(36) NULL,
  FOREIGN KEY (LastReviewSeen) REFERENCES Reviews(ID)
)
```

When the vendor opens the New Reviews page, the following queries are executed:

1. Use the vendor user ID to get their `LastReviewSeen` ID.
2. Get the `DatePosted` value associated with the `LastReviewSeen` review.
3. Use that `DatePosted` value to get the new reviews:

```sql
SELECT *
FROM Reviews
WHERE Reviews.VendorID = ? 
  AND Reviews.DatePosted > ?
```

4. Update `LastReviewSeen` to the last review on the page.

```sql
UPDATE User
  SET LastReviewSeen = ?
```

Issue with this implementation: If a review was posted at the exact same second as the `LastReviewSeen` review, that review will be skipped.

**Comment by Wenhuan2516** [comment]
Hi Makoto, your idea is really good. I will try to implement this feature today.

**Comment by Wenhuan2516** [comment]
Just noticed that!
