### ISSUE TITLE
Change UUID fields from binary type to string type

### ISSUE THREAD

**Issue by MakotoE** [bcfoodapp/streetfoodlove#40]
This involves two steps:

1. The database schemas should be edited so that any UUID column type is changed from `BINARY(16)` to `CHAR(36)` because a UUID is 36 characters long.
2. The `UUID` type in the Go code needs to be changed so that `Scan()` inputs a string representation and `Value()` returns a string representation.

**Comment by silviacasaburi** [comment]
Hi team, just an update; I have finished the Database update and working on the second task. Will probably finish tomorrow night and will submit both together for review. 
Let me know if you have any questions.
Silvia

**Comment by MakotoE** [comment]
Closed by https://github.com/bcfoodapp/streetfoodlove/pull/105
